package com.opt.model.constant;

public enum Tag {
    AGE, ALONE, AMAZING, ANGER, ANNIVERSARY, ARCHITECTURE, ART_FAVORITE, ATTITUDE, //
    BEAUTY, BEST, BIRTHDAY, BRAINY, BUSINESS, //
    CAR, CHANCE, CHANGE, CHRISTMAS, COMMUNICATION, COMPUTERS, COOL, COURAGE, //
    DAD, DATING, DEATH, DESIGN, DIET, DREAMS, //
    EASTER, EDUCATION, ENVIRONMENTAL, EQUALITY, EXPERIENCE, //
    FAILURE, FAITH, FAMILY, FAMOUS, FATHERS_DAY, FEAR, FINANCE, FITNESS, FOOD, FORGIVENESS, FREEDOM, FRIENDSHIP_FAVORITE, FUNNY, FUTURE, //
    GARDENING, GOD, GOOD, GOVERNMENT, GRADUATION, GREAT, //
    HAPPINESS, HEALTH, HISTORY, HOME, HOPE, HUMOR, //
    IMAGINATION, INDEPENDENCE, INSPIRATIONAL, INTELLIGENCE, //
    JEALOUSY, //
    KNOWLEDGE, //
    LEADERSHIP, LEARNING, LEGAL, LIFE_FAVORITE, LOVE_FAVORITE, //
    MARRIAGE, MEDICAL, MEMORIAL_DAY, MEN, MOM, MONEY, MORNING, MOTHERS_DAY, MOTIVATIONAL_FAVORITE, MOVIES, MOVING_ON, MUSIC, //
    NATURE, NEW_YEARS, //
    PARENTING, PATIENCE, PATRIOTISM, PEACE, PET, POETRY, POLITICS, POSITIVE, POWER, //
    RELATIONSHIP, RELIGION, RESPECT, ROMANTIC, //
    SAD, SAINT_PATRICKS_DAY, SCIENCE, SMILE, SOCIETY, SPACE, SPORTS, STRENGTH, SUCCESS_FAVORITE, SYMPATHY, //
    TEACHER, TECHNOLOGY, TEEN, THANKFUL, THANKSGIVING, TIME, TRAVEL, TRUST, TRUTH, //
    VALENTINES_DAY, VETERANS_DAY, //
    WAR, WEDDING, WISDOM_FAVORITE, WOMEN, WORK//
}
